#!/bin/bash

# https://github.com/twerth/ir_black/blob/master/colors/ir_black.vim

PAL_NAME="ir_black"

PAL_BACKGROUND="#000000"
PAL_FOREGROUND="#f6f3e8"

# black dark/light
PAL_COLOR0="#4E4E4E"
PAL_COLOR8="#7C7C7C"

# red dark/light
PAL_COLOR1="#FF6C60"
PAL_COLOR9="#FFB6B0"

# green dark/light
PAL_COLOR2="#A8FF60"
PAL_COLOR10="#CEFFAB"

# yellow dark/light
PAL_COLOR3="#FFFFB6"
PAL_COLOR11="#FFFFCB"

# blue dark/light
PAL_COLOR4="#96CBFE"
PAL_COLOR12="#B5DCFE"

# magenta dark/light
PAL_COLOR5="#FF73FD"
PAL_COLOR13="#FF9CFE"

# cyan dark/light
PAL_COLOR6="#C6C5FE"
PAL_COLOR14="#DFDFFE"

# white dark/light
PAL_COLOR7="#EEEEEE"
PAL_COLOR15="#FFFFFF"

