#!/bin/bash

# https://github.com/solarized/xresources/blob/master/Xresources.light

S_BASE03="#002b36"
S_BASE02="#073642"
S_BASE01="#586e75"
S_BASE00="#657b83"
S_BASE0="#839496"
S_BASE1="#93a1a1"
S_BASE2="#eee8d5"
S_BASE3="#fdf6e3"

S_YELLOW="#b58900"
S_ORANGE="#cb4b16"
S_RED="#dc322f"
S_MAGENTA="#d33682"
S_VIOLET="#6c71c4"
S_BLUE="#268bd2"
S_CYAN="#2aa198"
S_GREEN="#859900"

PAL_NAME="Solarized Light"

PAL_BACKGROUND="$S_BASE3"
PAL_FOREGROUND="$S_BASE00"  #use base02?

# black dark/light
PAL_COLOR0="$S_BASE02"
PAL_COLOR8="$S_BASE03"

# red dark/light
PAL_COLOR1="$S_RED"
PAL_COLOR9="$S_ORANGE"

# green dark/light
PAL_COLOR2="$S_GREEN"
PAL_COLOR10="$S_BASE01"

# yellow dark/light
PAL_COLOR3="$S_YELLOW"
PAL_COLOR11="$S_BASE00"

# blue dark/light
PAL_COLOR4="$S_BLUE"
PAL_COLOR12="$S_BASE0"

# magenta dark/light
PAL_COLOR5="$S_MAGENTA"
PAL_COLOR13="$S_VIOLET"

# cyan dark/light
PAL_COLOR6="$S_CYAN"
PAL_COLOR14="$S_BASE1"

# white dark/light
PAL_COLOR7="$S_BASE2"
PAL_COLOR15="$S_BASE3"

